export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SET_FEATURED_PROGRAM = "SET_FEATURED_PROGRAM";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const PUT_PROFILE = "PUT_PROFILE";
export const PROFILE_FETCHED = "PROFILE_FETCHED";

export const SET_ONGOING_PROGRAM = "SET_ONGOING_PROGRAM";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const SET_HOT_NEWS = "SET_HOT_NEWS";
export const SET_CATEGORY_PROGRAM = "SET_CATEGORY_PROGRAM";
